package models

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
)

type AutoGenerated struct {
	Db Mysqldb `json:"mysqldb"`
}

type Mysqldb struct {
	Name      string `json:"name"`
	Connector string `json:"connector"`
	Host      string `json:"host"`
	Port      int    `json:"port"`
	Database  string `json:"database"`
	Username  string `json:"username"`
	Password  string `json:"password"`
}

func SqlConnectionString() string {

	jsonFile, err := os.Open("config/dbcred.json")
	// if we os.Open returns an error then handle it
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("Successfully Opened users.json")
	// defer the closing of our jsonFile so that we can parse it later on
	defer jsonFile.Close()

	byteValue, _ := ioutil.ReadAll(jsonFile)

	fmt.Println(byteValue)
	// we initialize our Users array
	var users AutoGenerated

	// we unmarshal our byteArray which contains our
	// jsonFile's content into 'users' which we defined above
	json.Unmarshal(byteValue, &users)

	fmt.Println("User Type: ", users.Db.Database)
	dbConnString := fmt.Sprintf("%s:%s@/%s", users.Db.Username, users.Db.Password, users.Db.Database)
	fmt.Println(dbConnString)

	return dbConnString
}
